name: trio
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - numpy
  - scipy
  - pillow
  - tqdm
  - pyyaml
  - matplotlib
  - psutil
  - ipython
  - jupyter
  - pip
  - pip:
    - open_clip_torch
    - lpips
    - accelerate
    - tensorboard
    - lmdb
